# Generated by Django 5.0.6 on 2024-06-12 13:05

import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70)),
                ("description", models.TextField(max_length=1024)),
                (
                    "thumb",
                    imagekit.models.fields.ProcessedImageField(upload_to="albums"),
                ),
                ("tags", models.CharField(max_length=250)),
                ("is_visible", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(unique=True)),
                ("left", models.BooleanField()),
                ("right", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Contakt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nazwa", models.CharField(blank=True, max_length=70, null=True)),
                ("NrTel", models.CharField(blank=True, max_length=70, null=True)),
                ("EMail", models.CharField(blank=True, max_length=70, null=True)),
                ("GitHub", models.CharField(blank=True, max_length=200, null=True)),
                ("LinkedIn", models.CharField(blank=True, max_length=200, null=True)),
                ("Facebook", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Qualifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("photo", models.ImageField(upload_to="images/")),
                ("left", models.BooleanField()),
                ("right", models.BooleanField()),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=70, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1024, null=True),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="albums")),
                ("left", models.BooleanField()),
                ("right", models.BooleanField()),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Start",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=70, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1024, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlbumImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    imagekit.models.fields.ProcessedImageField(upload_to="albums"),
                ),
                (
                    "thumb",
                    imagekit.models.fields.ProcessedImageField(upload_to="albums"),
                ),
                ("alt", models.CharField(default=uuid.uuid4, max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("width", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                (
                    "slug",
                    models.SlugField(default=uuid.uuid4, editable=False, max_length=70),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="BastianWorld.album",
                    ),
                ),
            ],
        ),
    ]
